def get_qa_hints(lang: str = "en_US") -> str:
    if lang == "en_US":
        return (
            "CRITICAL: ont_dna is NOT a standalone CLI tool. Do NOT generate any shell command like "
            "'ont_dna --input ...' — no such command exists. "
            "ont_dna is a multi-step workflow executed entirely by the agent. "
            "To run it, the user simply describes their data in the chat (e.g. 'I have ONT DNA POD5 data, detect 5mCG') "
            "and the agent handles everything automatically.\n"
            "Workflow steps (run automatically in sequence):\n"
            "  1. dorado download — downloads the DNA basecall model and modification model\n"
            "  2. dorado basecaller — basecalls POD5 and calls modifications (e.g. 5mCG, 6mA)\n"
            "  3. samtools sort — coordinate-sorts the output BAM\n"
            "  4. samtools index — indexes the sorted BAM\n"
            "  5. samtools faidx — indexes the reference FASTA (only when reference is provided)\n"
            "  6. modkit extract — extracts per-read modification calls (always runs)\n"
            "  7. modkit pileup — site-level bedMethyl output (only when reference is provided)\n"
            "Input must be POD5 or modBAM — FASTQ is not supported. "
            "A reference genome is optional; without it modkit pileup and faidx steps are skipped.\n"
            "For IGV visualization: load the aligned BAM + BAI, plus the bedMethyl (.bed.gz + .tbi) for site-level tracks."
        )
    return (
        "重要提示：ont_dna 不是独立的命令行工具，不要生成任何类似 'ont_dna --input ...' 的命令，该命令不存在。"
        "ont_dna 是由 Agent 自动执行的多步骤工作流，用户只需在对话框中描述数据（如'我有 ONT DNA POD5 数据，检测 5mCG'），"
        "Agent 会自动完成所有步骤。\n"
        "工作流步骤（按序自动执行）：\n"
        "  1. dorado download — 下载 DNA basecall 模型和修饰模型\n"
        "  2. dorado basecaller — 对 POD5 进行 basecall 并调用修饰（如 5mCG、6mA）\n"
        "  3. samtools sort — 对输出 BAM 按坐标排序\n"
        "  4. samtools index — 索引排序后的 BAM\n"
        "  5. samtools faidx — 索引参考基因组（仅在提供参考序列时运行）\n"
        "  6. modkit extract — 提取每条 read 的修饰调用（始终运行）\n"
        "  7. modkit pileup — 输出位点级 bedMethyl（仅在提供参考序列时运行）\n"
        "输入必须是 POD5 或 modBAM，不支持 FASTQ。参考基因组可选，无参考时跳过 faidx 和 pileup 步骤。\n"
        "IGV 可视化：加载比对后的 BAM + BAI，加上 bedMethyl（.bed.gz + .tbi）作为甲基化轨道。"
    )
