
import os
import re
import subprocess

from configs.path_config import IMAGE_PATH
from tools.analyzers.file.base import FileAnalyzer


def _resolve_samtools_image() -> str | None:
    tool_dir = os.path.join(os.path.expanduser(IMAGE_PATH["image_store"]), "samtools")
    if not os.path.isdir(tool_dir):
        return None
    img_files = [f for f in os.listdir(tool_dir) if f.endswith((".img", ".sif"))]
    if not img_files:
        return None
    img_files.sort(key=lambda f: (0 if f.endswith(".img") else 1, f))
    return os.path.join(tool_dir, img_files[0])


def _build_singularity_cmd(bam_path: str, samtools_args: str) -> str:
    image_path = _resolve_samtools_image()
    bam_dir    = os.path.dirname(os.path.abspath(bam_path))
    if image_path:
        return (
            f"singularity exec "
            f"--bind {bam_dir}:{bam_dir} "
            f"{image_path} "
            f"samtools {samtools_args}"
        )
    print("[BamAnalyzer] No samtools image found, falling back to local samtools")
    return f"samtools {samtools_args}"


def _run(cmd: str, timeout: int = 120) -> tuple[str, str]:
    """
    Run a shell command in a NEW process group so that any signals (SIGTERM/SIGKILL)
    generated by singularity cleanup or OOM-killer cannot propagate to the parent
    Streamlit process.
    On timeout, the entire child process group is killed before re-raising.
    """
    import os
    import signal as _signal

    proc = subprocess.Popen(
        cmd,
        shell=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        start_new_session=True,  # isolate from parent process group
    )
    try:
        stdout, stderr = proc.communicate(timeout=timeout)
        return stdout, stderr
    except subprocess.TimeoutExpired:
        # Kill the entire process group (singularity + samtools children)
        try:
            os.killpg(os.getpgid(proc.pid), _signal.SIGTERM)
        except Exception:
            pass
        try:
            proc.kill()
            proc.communicate(timeout=3)
        except Exception:
            pass
        return "", f"Timeout after {timeout}s"


def _parse_flagstat(text: str) -> dict:

    stats = {}
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        # 提取第一个数字（QC-passed reads 计数）
        m_count = re.match(r'^(\d+)\s*\+\s*\d+\s+(.+)', line)
        if not m_count:
            continue
        count = int(m_count.group(1))
        desc  = m_count.group(2).lower()

        if "in total" in desc:
            stats["total_reads"] = count
        elif "primary" in desc and "mapped" in desc and "duplicate" not in desc:
            stats["primary_mapped"] = count
        elif "mapped" in desc and "primary" not in desc and "duplicate" not in desc:
            stats["mapped_reads"] = count
        elif "secondary" in desc:
            stats["secondary"] = count
        elif "supplementary" in desc:
            stats["supplementary"] = count

    # 映射率（从 "mapped (X.XX%...)" 中提取）
    m_rate = re.search(r'mapped\s*\(([0-9.]+)%', text)
    if m_rate:
        stats["mapped_rate"] = round(float(m_rate.group(1)), 2)
    return stats


def _parse_stats(text: str) -> dict:

    stats: dict = {}
    rl_dist: dict[int, int]   = {}
    qual_dist: dict[int, int] = {}

    for line in text.splitlines():
        if line.startswith("SN"):
            parts = line.split("\t")
            if len(parts) < 3:
                continue
            key = parts[1].strip().rstrip(":")
            val = parts[2].strip()
            if key == "average quality":
                try:
                    stats["avg_quality"] = round(float(val), 2)
                except ValueError:
                    pass
            elif key == "average length":
                try:
                    stats["avg_read_length"] = round(float(val), 1)
                except ValueError:
                    pass
            elif key == "reads examined":
                try:
                    stats["reads_examined"] = int(val)
                except ValueError:
                    pass

        elif line.startswith("RL\t"):
            # RL  <length>  <count>
            parts = line.split("\t")
            if len(parts) >= 3:
                try:
                    rl_dist[int(parts[1])] = int(parts[2])
                except ValueError:
                    pass

        elif line.startswith("QUAL\t"):
            # QUAL  <cycle>  <q0_count>  <q1_count> ... <q40_count>
            parts = line.split("\t")
            if len(parts) < 3:
                continue
            for q_idx, cnt_str in enumerate(parts[2:], start=0):
                try:
                    cnt = int(cnt_str)
                    if cnt > 0:
                        qual_dist[q_idx] = qual_dist.get(q_idx, 0) + cnt
                except ValueError:
                    pass

    if rl_dist:
        stats["read_length_dist"] = rl_dist
    if qual_dist:
        stats["quality_dist"] = qual_dist
    return stats


class BamAnalyzer(FileAnalyzer):
    def analyze(self, file_path: str) -> dict:
        if not os.path.isfile(file_path):
            return {"error": f"File not found: {file_path}"}

        result = {"file": os.path.basename(file_path), "type": "bam"}

        try:
            # 1. flagstat
            cmd_flag = _build_singularity_cmd(file_path, f"flagstat {file_path}")
            out_flag, err_flag = _run(cmd_flag)
            if out_flag:
                result.update(_parse_flagstat(out_flag))
            else:
                result["flagstat_error"] = err_flag[:200]
        except Exception as e:
            result["flagstat_error"] = str(e)

        try:
            cmd_stats = _build_singularity_cmd(file_path, f"stats {file_path}")
            out_stats, err_stats = _run(cmd_stats, timeout=180)
            if out_stats:
                result.update(_parse_stats(out_stats))
            else:
                result["stats_error"] = err_stats[:200]
        except Exception as e:
            result["stats_error"] = str(e)

        return result
