[theme]
base            = "light"
primaryColor    = "#4c8bf5"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f4ff"
textColor       = "#1a1f2e"
font            = "sans serif"

[server]
headless = true
maxUploadSize = 10240
address='0.0.0.0'
port=50027
